[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Uncomment for automatic flash

[unstable]
build-std = ["std", "panic_abort"]

[env]
# Let esp-idf-sys download and manage ESP-IDF
ESP_IDF_VERSION = "v5.2.3"
ESP_IDF_TOOLS_INSTALL_DIR = "global"
